### ISSUE TITLE
[PE-D] Different error messages for invalid index

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2103T-W11-4/tp#140]
Using delete as an example, if delete 0 is used, the application shows an invalid command format message.

![image.png](https://raw.githubusercontent.com/cashewnade/ped/main/files/9ca6ef45-2d5c-45f0-aa12-1c5b5d512a48.png)

If delete 7 is used, when the list has only 6 people, an invalid index message is shown.

![image.png](https://raw.githubusercontent.com/cashewnade/ped/main/files/9365d3ab-8d8e-4d3d-bfe7-79cdfe98cbb6.png)

Since delete only takes in one variable, which is index, I believe for either case the error messages should be the same. Either invalid command format or invalid index.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: cashewnade/ped#14

**Comment by SimJM** [comment]
Thank you for spotting this. It is mentioned in the error message that index must be a positive integer. Hence, entering '0' will lead to an invalid command format.
On the other hand, 'delete 7' will return 'The person index provided in invalid' as '7' is a positive integer (valid command format), but it is out of range, hence invalid.
